apiVersion: v2
appVersion: 1.0.0
dependencies:
- name: influxdb2
  repository: https://helm.influxdata.com/
  version: 2.0.9
- name: chronograf
  repository: https://helm.influxdata.com/
  version: 1.2.1
name: influx-bundle
version: 1.0.0