# This is a basic workflow that is manually triggered

name: PR Workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
 pull_request:
  types:
  - opened
  - edited


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout the code
      uses: actions/checkout@master
    - name: Setup Maven
      uses: stCarolas/setup-maven@v4.2
      with:
        maven-version: 3.8.2
    - name: Maven Package - Native mode
      working-directory: app
      run: mvn package -q -Pnative
    - name: Build Quarkus Native container
      working-directory: app
      run: docker build -f src/main/docker/Dockerfile.native -t quarkus/crypto-value .
