# This is a basic workflow that is manually triggered

name: Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'Release Name'
        default: 'crypto-price-analyzer'
        required: true
        type: choice
        options: 
        - crypto-price-analyzer
      version:
        description: 'Release Version'
        default: 'vX.X.X'
        required: true
        type: text
      push_image:
        type: boolean
        default: 'true'
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@master
    - name: Setup Maven
      uses: stCarolas/setup-maven@v4.2
      with:
        maven-version: 3.8.2
    - name: Maven Package - Native mode
      working-directory: app
      run: mvn package -q -Pnative
    - name: Build Quarkus Native container
      working-directory: app
      run: docker build -f src/main/docker/Dockerfile.native -t ${{ github.event.inputs.name }}:${{ github.event.inputs.version }} .
    - name: Save Image
      run: docker save -o image.tar ${{ github.event.inputs.name }}.tar
    - name: Check image weight
      run: ls -hs image.tar
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: image.tar
        path: image.tar
